---
#This role is to check that development and staging defaults gpg info and
#credentials are not used when running the app and mon playbooks for
#production.

- include: validate_users.yml

- include: validate_gpg_info.yml
  with_items:
    - "{{ securedrop_app_gpg_fingerprint }}"
    - "{{ ossec_gpg_fpr }}"

- include: validate_ossec_info.yml
