---
- name: Validate OSSEC Admin email address.
  assert:
    that:
      - "'@' in ossec_alert_email"
      - ossec_alert_email != "ossec@ossec.test"
    msg: >-
      OSSEC Admin email address must be valid.
      This address is used to receive OSSEC notifications.

- name: Validate SASL username for OSSEC config.
  assert:
    that:
      # Ensure not the dummy value specified in example vars file.
      - sasl_username != "test"
      - "'@' not in sasl_username"

- name: Validate SASL password for OSSEC config.
  assert:
    that:
      # Ensure not the dummy value specified in example vars file.
      - sasl_password != "password123"
      - sasl_password|length >= 8
    msg: >-
      Password for OSSEC email account must be strong.

- name: Validate SASL domain.
  assert:
    that:
      - sasl_domain is defined
      # The pipe lookup will fail if command returns non-zero.
      - lookup('pipe', 'host '+sasl_domain)
    msg: >-
      The SASL domain failed during lookup. This is typically the
      portion of the email address after the '@' symbol, although
      configurations may vary.

- name: Validate SMTP relay.
  assert:
    that:
      - smtp_relay is defined
      # The pipe lookup will fail if command returns non-zero.
      - lookup('pipe', 'host '+smtp_relay)
    msg: >-
      The SMTP relay domain failed during lookup. This domain
      is the server contacted for authentication in order to send
      OSSEC email notifications.
